### ISSUE TITLE
Couchbase: add additional fields

### ISSUE THREAD

**Issue by dev-samiur** [GluuFederation/gluu-admin-ui#101]
buckets
defaultBucket
passwordEncryptionMethod
sslTrustStoreFile
sslTrustStoreFormat
sslTrustStorePin
userName
userPassword

**Comment by syntrydy** [comment]
@dev-samiur if **buckets** and  **defaultBucket** are missing that implies that the backing data source is not Couchbase. In that case, we can display a message to inform the user.
