### ISSUE TITLE
JSON Properties --> Server Properties

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-admin-ui#108]
"JSON Properties" does not really make much sense.

There should be a section called "Server Properties"

In this section, there should be links for: "Auth Server", "FIDO", and "SCIM".

Potentially plugins will add additoinal sections for Server Properties.

In each Server Property individual page, there should be groupings. For example, for the Auth Server, you may want to group according to OpenID Endpoints, UMA Settings, Backwards Compatability Settings, etc.

**Comment by syntrydy** [comment]
Duplicate with https://github.com/GluuFederation/gluu-admin-ui/issues/87
