### ISSUE TITLE
A declarative way of defining the menu pattern for each plugin

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#110]
The plugins should be Displayed with their parent-menus and child-menus.

![image](https://user-images.githubusercontent.com/32794267/117284712-c2ad8580-ae84-11eb-91d8-98c45f54374e.png)

**Comment by syntrydy** [comment]
A complete example is available at https://github.com/GluuFederation/gluu-admin-ui/blob/plugin_development/plugins/services-plugin/plugin-metadata.js
