### ISSUE TITLE
Create `Schema` plugin

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#115]
![image](https://user-images.githubusercontent.com/32794267/117925150-734bd700-b314-11eb-923e-b054ba04bc88.png)

**Comment by duttarnab** [comment]
@nynymike @syntrydy 

Please reply to the following questions regarding `Schema Plugin`:

1. Person -- This will be similar to Add person, Import person, Manage Person, Manage Groups of oxtrust. Please confirm.
![image](https://user-images.githubusercontent.com/32794267/118008929-352dd200-b36b-11eb-9e37-550c7c1efd12.png)

2. Client -- I think this feature to add/edit OIDC client. Please confirm.
3. Token -- we need to show current active `access_token` and `api-protection-token` here. Please confirm.
4. FIDO Devices -- Is there any application showing FIDO Devices? we can copy the features from there.

**Comment by nynymike** [comment]
Schema relates to entity management. For example, if we have a person entity, what properties does that entity have? In the old server, we had a section called "Attribute":

![image](https://user-images.githubusercontent.com/3717101/118146390-2deede80-b3d4-11eb-801c-e5a589b18b6b.png)

This is really the schema for a person--i.e. what are the attributes (properties) of a person. However, customers may want to manage the schema of other objects besides a Person entity. It's quite common to have custom client properties. Also, you may have special information you want to store in a refresh token.

**Comment by duttarnab** [comment]
Completed Person schema.

**Comment by duttarnab** [comment]
Closing as Person schema done.
