### ISSUE TITLE
Configuration Logging and Commenting

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/gluu-admin-ui#123]
All changes to config changes from the Web UI or API's should be logged in the UI audit log. It would also be good if before saving any config changes, the admin was forced to put a comment. The authenticated user and client_id should also be recorded in the logs.

**Comment by syntrydy** [comment]
The base structure for logging and commenting is now available.
The concept is already applied to OpenID connect clients' resources.

Now we have to create task to apply it to other resources.
