### ISSUE TITLE
Refactor OIDC handling code in `admin-ui`

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#140]
1. Check how authentication, get user-info, get access token , get api token and logout works in admin-ui.
2. The current code in `AuthenticatedRouteSelector.js`,  `AppAuthProvider.js`, `ByeBye.js` etc.. handling OIDC part is unorganized full of if-else. It will be better if we use or create code like https://www.npmjs.com/package/react-oidc-client wrapping different stages of the OIDC process behind the scenes.

Or perhaps we can use [AppAuth-JS](https://github.com/openid/AppAuth-JS) as the OpenID Connect client code.

**Comment by syntrydy** [comment]
I don't think this is the job of the admin-UI project.
Okta is a sass app and they have tons of custom libraries to helps their customers with okta integration. Gluu is not at that level yet, as of now, we don't have saas yet. I when Gluu will go sass, the need for such libraries will show up and the whole team will decide the best way to do it.
Personally, that is not the job of the admin-UI project, admin-UI can use such tool i=only if it exists.

**Comment by duttarnab** [comment]
Noted. Let's close this ticket as it is not a priority item at present. We can work on this when our custom front-channel app client is ready to wrap different stages of the OIDC process.
