### ISSUE TITLE
OIDC: saga error

### ISSUE THREAD

**Issue by dev-samiur** [GluuFederation/gluu-admin-ui#146]
![Screenshot_20210614_030604](https://user-images.githubusercontent.com/67631118/121821876-a25fba80-ccbd-11eb-9af1-5fe9e2be2c1c.png)

Fix type error in oidc saga

**Comment by duttarnab** [comment]
Duplicate ticket: https://github.com/GluuFederation/gluu-admin-ui/issues/136
