### ISSUE TITLE
Persistence: Add RDBMS support

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-admin-ui#150]
RDBMS support is very important for Aurora.

**Comment by duttarnab** [comment]
We need following SQL Database configuration endpoints in `config-api`. 

1. `GET` - Gets list of existing SQL (Mysql) configurations. The configuration should have the following fields.

| Field Name | Datatype | Example |
|--------------|-----------|-----------|
| configId | string | auth_mysql_server |
| userName | string | jans |
| userPassword | string | X4BYp4GMWo47dO8feHwC/w== |
| connectionUri | array | ["jdbc:mysql://localhost:3306/jans"] |
| schemaName | string | jans |
| serverTimezone | string | UTC |
|useServerPrepStmts|int|500|
|prepStmtCacheSqlLimit|int|1024|
|cachePrepStmts|boolean|false|
|cacheResultSetMetadata| boolean|false|
|metadataCacheSize| int| 500|
|passwordEncryptionMethod| string|SSHA-256|
|maxTotal| int | 40|
|maxIdle| int|15|
|minIdle|int|5|
|createMaxWaitTimeMillis|int|20000|
|maxWaitTimeMillis|int|20000|
|minEvictableIdleTimeMillis|int|1800000|
|binaryAttributes|array| ["objectGUID"]|
|certificateAttributes|array|["userCertificate"]|

**Comment by duttarnab** [comment]
Admin-UI with MySql database running on `jans-ui.jans.io`
