### ISSUE TITLE
Custom Script - Add/Edit Custom Script 

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/gluu-admin-ui#18]
Currently, it is only possible to list custom scripts and also show the detail of a row.

This task consists of implementing the adding and edition of a custom script.
![image](https://user-images.githubusercontent.com/7513418/109527901-77f24480-7ab4-11eb-8379-7457ba8fa5ad.png)
- A click on the plus sign should open the Script add form
- A click on the edit sign from an existing row should open the Script edit form

**Comment by duttarnab** [comment]
Done
