### ISSUE TITLE
Attribute UI : Add support to modify jansHideOnDiscovery 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/gluu-admin-ui#19]
`jansAttr` OC has new attributes `jansHideOnDiscovery` which has to be editable via UI. 

https://github.com/JanssenProject/jans-auth-server/issues/37

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/112478988-d8536980-8d74-11eb-9988-3754a59bb70d.png)
