### ISSUE TITLE
Sidebar Panel UI

### ISSUE THREAD

**Issue by vwgs94** [GluuFederation/gluu-admin-ui#200]
Select sidebar panel fonts, font sizes and color scheme that correspond to tree structure

<img width="250" alt="Screen Shot 2021-08-18 at 1 06 43 AM" src="https://user-images.githubusercontent.com/17362261/129861875-b7336aa7-318a-4d21-b5a5-aefc7e087afb.png">

**Comment by vwgs94** [comment]
Mock-up

Fonts used: Helvetica Neue Bold, Helvetica Neue Regular, Helvetica Neue Light

<img width="193" alt="Screen Shot 2021-08-21 at 1 05 29 AM" src="https://user-images.githubusercontent.com/17362261/130315260-676ae47b-345c-4f4b-a97d-80fd74c8367e.png">

**Comment by fausto-gluu** [comment]
Done

**Comment by duttarnab** [comment]
Tested on https://admin-ui-test.gluu.org/admin
