### ISSUE TITLE
Closing Sidebar Panel

### ISSUE THREAD

**Issue by vwgs94** [GluuFederation/gluu-admin-ui#202]
An ‘X’ button to close the sidebar panel when it is expanded could be more intuitive. The hamburger button is fine for expanding the sidebar panel when it is collapsed.

<img width="336" alt="Screen Shot 2021-08-18 at 1 11 35 AM" src="https://user-images.githubusercontent.com/17362261/129862735-298dca26-0250-451e-b176-6eaac8d4d345.png">

**Comment by vwgs94** [comment]
Example:

'X' button to close sidebar panel:

<img width="392" alt="Screen Shot 2021-08-21 at 1 18 21 AM" src="https://user-images.githubusercontent.com/17362261/130315619-f49ed389-9872-4001-824c-9fe879371266.png">

**Comment by duttarnab** [comment]
Working on https://admin-ui-test.gluu.org/admin

**Comment by duttarnab** [comment]
![image](https://user-images.githubusercontent.com/32794267/132805524-e3cd71e9-d0b2-4ba6-86ae-18f2c59260a1.png)
