### ISSUE TITLE
Provides proper names for `grant Types` and `Scopes` on client registration page

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#208]
![image](https://user-images.githubusercontent.com/32794267/132734529-dc76ca4f-942a-4341-867a-b27bc88d118a.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/132735303-9f7b6a86-8272-4714-89ba-a2e1161ab585.png)
