### ISSUE TITLE
For `Add OIDC Clients` remove validation for https protocol 

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#209]
For `Add OIDC Clients` remove validation for only https protocol in multiple adds of `post_logout_redirect_uris` and `Redirect Uris`. Both `http` and `https` urls should be allowed.

![image](https://user-images.githubusercontent.com/32794267/132735386-b5286e52-4440-4e05-888d-37d4c989842d.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/132737336-89c8c038-3b02-40aa-bfa6-62aec2a18823.png)

**Comment by syntrydy** [comment]
@duttarnab we remove validation or do we add validation for both HTTP and HTTPS? I think @nynymike said to remove all validation both fields

**Comment by duttarnab** [comment]
**Mike's Comments:** 
At this point, there are use cases for using my https, and other schemas, like myapp://callback

If a user wants to put in some crazy callback, by hand, let him

and in fact, if the server is using locahost, in fact http may be fine, because the communication never traverses the network

but in any case, if you want to use http, who are we to say you can’t…
