### ISSUE TITLE
`Add OIDC Clients`: move the tiny fields at the location so that they are visible to users.

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#211]
1.  Move tiny fields like checkboxes to top or the location where they are not missed by users. We can get ideas from oxtrust UI.

2. “Persist Client Authorizations” can be moved to client attributes

3. “trusted clients” should be renamed… it’s hard to know what that means. I’d say “Skip Authorization Flow”

![image](https://user-images.githubusercontent.com/32794267/132736800-1b4ade43-cea3-44d5-9c14-51146feb9472.png)

**Comment by syntrydy** [comment]
**Persist Client Authorizations** can be moved to client attributes, client attributes are handled on the backends as a JSON object, and Persist Client Authorizations field is not part of that JSON. Moving it on that section will confuse users
If we really want to move it, the same action should be done on the backend before

you can check that by exploring the structure of an OIDC client in the database

**Comment by duttarnab** [comment]
![image](https://user-images.githubusercontent.com/32794267/133234132-0dfef668-7e2c-42ee-a592-db688e8527c4.png)

Do you think we need backend changes to move that field here?

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/133650403-660c1d7e-1e3b-4f04-9841-b085f231f08d.png)
