### ISSUE TITLE
Need to substring search the client_id on `OIDC clients` search page

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#213]
Also, in the client search section, when I put in a81f, which is part of a client id… nothing is returned.

We need to substring search the client_id, because obviously people may want to search by client_id…

Can someone please open issues for all the things I raised above

But I really wish you guys would be thinking about this stuff.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/132745944-9030af01-0102-4fd5-b8b0-25f4c6b6ba2c.png)
