### ISSUE TITLE
`Scripts`:  Adding a new script redirects from 404 page

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#217]
1. Go to `Admin --> Scripts` to add a new Script.
2. Fill the form and click on `Apply` button
3. It redirect to 404 page.
![image](https://user-images.githubusercontent.com/32794267/132812908-3f32e447-e2da-467e-86e9-557e61c40c32.png)

**Comment by syntrydy** [comment]
fixed
