### ISSUE TITLE
Add/Edit Scope

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/gluu-admin-ui#22]
Currently, it is only possible to list all Scopes and also show the detail of a row.

This task consists of implementing the add and edits a Scope.

![image](https://user-images.githubusercontent.com/7513418/109526677-21d0d180-7ab3-11eb-88a6-fe17464a88cf.png)

- A click on the plus sign should open the scope add form
- A click on the edit sign from an existing row should open the Scope edit form

**Comment by pujavs** [comment]
Add/Edit/Delete Scope Feature implemented and tested
[Scope.xlsx](https://github.com/GluuFederation/gluu-admin-ui/files/6222268/Scope.xlsx)

**Comment by duttarnab** [comment]
1. Scopes functionality should be similar to Gluu auth-server `openid` scopes.
2. `id` field not required.
3. `spontaneousClientScopes` is missing.
4. UMA scope snot required in `admin-ui`
5. Form validation missing for scopes

**Comment by pujavs** [comment]
Looking into the above issue

**Comment by duttarnab** [comment]
1. `id` not required 
2. ok will test after changes are done
3. yes
4. ok

**Comment by pujavs** [comment]
Changes done
1) id field removed from GUI
2) UMA scope type as select option and 'umaAuthorizationPolicies drop down removed
3) Rectified validation for mandatory fields

![image](https://user-images.githubusercontent.com/43700552/113413214-bb9fdd00-93d7-11eb-8267-cac0d77dc93c.png)
![image](https://user-images.githubusercontent.com/43700552/113413345-1b968380-93d8-11eb-9421-5b6506ebb2da.png)
![image](https://user-images.githubusercontent.com/43700552/113413352-251feb80-93d8-11eb-83ca-d2c543607f59.png)
![image](https://user-images.githubusercontent.com/43700552/113413406-408af680-93d8-11eb-8dd4-69e93e9c118d.png)
