### ISSUE TITLE
`OIDC Clients`: View OIDC clients should not have `Apply` button

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#220]
`OIDC Clients`: View OIDC clients should not have `Apply` button.

![image](https://user-images.githubusercontent.com/32794267/132818261-ee234809-8bd3-46df-baee-54d4834811ae.png)

**Comment by syntrydy** [comment]
What is the reason behind this? Someone viewing an object can eventually edit it.
