### ISSUE TITLE
`Scopes`: Add new scopes not working

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#223]
`Scopes`: Add new scopes not working

**Comment by syntrydy** [comment]
This is working

**Comment by duttarnab** [comment]
Shared issue video on PM

**Comment by duttarnab** [comment]
The pagination shows `1 - 20 of 20`. But there total 67 rows. It should show `1 - 20 of 67`.
The user should be able to navigate to the next page by clicking on the ` >` button (which is disabled even though there are 67 items).

**Comment by duttarnab** [comment]
opened https://github.com/GluuFederation/gluu-admin-ui/issues/230 for pagination issue
