### ISSUE TITLE
`JSON Properties`: Unable to edit field values like `Logging Level`, `Logging Layout` etc

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#245]
1.  Go to `OAuth server` --> `Cofiguration` --> `Properties`
2. Modify fields like `Logging Level`, `Logging Layout` 
3. Click on `correct` button
4. The value reverts back to old value

Note: `Logging Level` was changed from `TRACE` to `DEBUG`
`Logging Layout` was changed from `text` to `json`

**Comment by syntrydy** [comment]
Fixed, please test on admin-ui-test

**Comment by duttarnab** [comment]
Fixed
