### ISSUE TITLE
Fetch couchbase configuration page.

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/gluu-admin-ui#26]
Fetch Couchbase configuration page.
Currently, the design is already available, have to fetch data from config-API and display.

![image](https://user-images.githubusercontent.com/7513418/109529645-3a8eb680-7ab6-11eb-8c39-cbaa955d15dc.png)

**Comment by duttarnab** [comment]
Assigning to Samiur. As he already completed the previous tasks
