### ISSUE TITLE
Log out feature in admin-ui

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#31]
Log out flow for admin-ui

Pre-requisite: the openid client should be registered with `frontchannel_logout_uri` and `post_logout_redirect_uri`.

![image](https://user-images.githubusercontent.com/32794267/110468003-b5cb1a80-80fd-11eb-9dd1-6d59a06c47b9.png)

**Comment by duttarnab** [comment]
@nynymike please review logout flow.

**Comment by duttarnab** [comment]
actor User
User->Browser:
Browser->jans-admin-ui-frontend:Click on logout menu
jans-admin-ui-frontend->jans-admin-ui-backend: Request for /end_session_endpoint?state=<state>
jans-admin-ui-backend->jans-admin-ui-backend: create end_session_endpoint with state and post_logout_redirect_uri

jans-admin-ui-backend->jans-admin-ui-frontend: end_session_endpoint

jans-admin-ui-frontend->jans-auth-server-1: execute end_session_endpoint

jans-auth-server-1->jans-auth-server-1: The auth-server renders `iframe` calling `frontchannel_logout_uri` handler to clear all session data at frontend


jans-auth-server-1->jans-admin-ui-frontend: redirect to post_logout_redirect_uri

**Comment by yuriyz** [comment]
As discussed in chat

![image](https://user-images.githubusercontent.com/2013070/110471051-514f9180-80e4-11eb-87a3-2f14c1c5768e.png)

**Comment by duttarnab** [comment]
Updated Sequence diagram:

actor User
User->Browser:
Browser->jans-admin-ui-frontend:Click on logout menu
jans-admin-ui-frontend->jans-admin-ui-frontend: Create /end_session_endpoint?state=<state>&post_logout_redirect_uri=<post_logout_redirect_uri>

jans-admin-ui-frontend->jans-auth-server-1: execute end_session_endpoint

jans-auth-server-1<->jans-admin-ui-frontend: Iframe calling frontchannel_logout_uri handler to clear all session data at frontend

jans-auth-server-1->jans-admin-ui-frontend: redirect to post_logout_redirect_uri
