### ISSUE TITLE
Oxtrust `Add Attributes` screen has more fields then `admin-ui` `Add Attributes` screen.

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#54]
Oxtrust `Add Attributes` screen has more fields than `admin-ui` `Add Attributes` page.

The missing fields should be added in `admin-ui` `Add Attributes` page.

**Oxtrust `Add Attributes`** 
![image](https://user-images.githubusercontent.com/32794267/112463769-ab10b680-8d88-11eb-9048-3b8dcd6e5e1b.png)

**`admin-ui` `Add Attributes`** 
![image](https://user-images.githubusercontent.com/32794267/112463821-b82da580-8d88-11eb-80d7-cf519c49cc33.png)

**Comment by syntrydy** [comment]
Fixed
