### ISSUE TITLE
SMTP: Save not working

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#57]
The save operation in `SMTP` screen not working.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/112528493-7f9bc500-8da4-11eb-8cc3-dbb41caad424.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/112548116-027c4a00-8dbc-11eb-9572-49e802a0b926.png)

**Comment by syntrydy** [comment]
Fixed
