### ISSUE TITLE
Acr: There should be a dropdown in this form instead of textbox.

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#61]
There should be a dropdown in this form listing all present acrs. (Similar to oxtrust)

In oxtrust
![image](https://user-images.githubusercontent.com/32794267/112468995-f1691400-8d8e-11eb-975a-71af072cc7de.png)

Admi-UI
![image](https://user-images.githubusercontent.com/32794267/112469041-ff1e9980-8d8e-11eb-88b4-9e21121b9bfb.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/112558546-4e84ba00-8dcf-11eb-8d3b-208c85bb3cc6.png)

**Comment by syntrydy** [comment]
Fixed. Noted that only active authentication script is available in the dropdown
