### ISSUE TITLE
Attribute Screen Testing

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/gluu-admin-ui#72]
[Attribute.xlsx](https://github.com/GluuFederation/gluu-admin-ui/files/6259087/Attribute.xlsx)
See attached excel
1) List Screen: Field mismatch
2) Description should be textbox
3) Enable tooltip for this attribute: checkbox missing
4) Data type - Drop Down Value Mismatch
5) Mandatory fields mismatch
6) Save - AdminUI allows to save any new attribute however oxTrust gives error stating that 'Atrribute not defined in LDAP schema. Is this check required?
7) Edir - Not working

**Comment by syntrydy** [comment]
@dev-samiur you don't have to implement point 3(that field is no longer needed)
On point 2, the description should be **textarea**. 
4-Data type - Drop Down Value Mismatch: here we just have to make sure all dropdown items are present, the order doesn't matter. The old UI wasn't a perfect model.
On point 6: The documentation should take on this one, the user must add the attribute in schema first before filling this form. This is only true when the data storage is LDAP.

**Comment by dev-samiur** [comment]
For the task no. 7: The bug, while editing an attribute is caused only if the value of usageType filed set to”Not Defined”. Server is responding with 500 in this case. Same while trying to save an attribute with usageType= Not Defined, server responding with 500. So I believe there is some exceptions need to be handled in the backend.
