### ISSUE TITLE
Custom Script Testing

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/gluu-admin-ui#74]
[CustomScript.xlsx](https://github.com/GluuFederation/gluu-admin-ui/files/6259140/CustomScript.xlsx)

See attached excel
1) View 
1.1) Script name header should be alphabetically sorted making it easier for user. 
1.2) All bold Script names also does not look appropriate
2) Script name: Missing => End Session, Post Authentication, Revoke Token,UMA RPT Claims
Extra Script in Admin => Update Token
3) Missing Fields
3.1) 'Select SAML ACRS' multivalue selection dropdown for Person Authentication Script
3.2) 'Location Type' dropdown is missing
3.3) INTERACTIVE' dropdown is missing for Person Authentication Script
4) Mandatory fields mismatch

**Comment by duttarnab** [comment]
1.1) This design has been changed
1.2) This design has been changed
2. Not Applicable
3. Done
4. Done
