### ISSUE TITLE
LDAP Testing

### ISSUE THREAD

**Issue by pujavs** [GluuFederation/gluu-admin-ui#76]
[Ldap.xlsx](https://github.com/GluuFederation/gluu-admin-ui/files/6259161/Ldap.xlsx)
See attached excel
1) View : Fields mismatch as compared to oxTrust
2) Even though the logged in user has the write scope there is no option to Add/Edit
3) No option to Activate/Deactivate . Is this same as Enable checkbox
4) No option to 'Test Configuration'

**Comment by duttarnab** [comment]
1. View : Fields mismatch as compared to oxTrust - `All fields are present`
2. Even though the logged in user has the write scope there is no option to Add/Edit -- `Add/Edit option present`
3. No option to Activate/Deactivate . Is this same as Enable checkbox - `yes`
4. No option to 'Test Configuration' - `Test Configuration` Added
