### ISSUE TITLE
License Enforcement

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-admin-ui#80]
As Gluu-Admin UI is a commercial component, I'd like to introduce license enforcement. We're looking at a license SaaS tool called [LicenseSpring](https://licensespring.com/)

The basic idea is that on installation of an instance of Gluu 5, you'd get a 30 day trial license. After which, the admin-ui would shut off (unless you updated the license file). 

Also, we'd like to be able to license plugins: Casa, Passport, Shibboleth SAML.  For example, the license could have attributes--which components you are licensed to use.

**Comment by duttarnab** [comment]
Integrated license Spring in Admin-UI backend.
