### ISSUE TITLE
Implement "Apply" method for config changes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-admin-ui#88]
It would be better if instead of implementing changes immediately, admin made changes in the console, and when they were ready to "Apply" them, they were forced to review, and give a comment (which should be logged). After apply, the respective REST commands should be issued with respective notificaiton of success.

**Comment by duttarnab** [comment]
After the user fills the config form and clicks on the save button, `admin-ui` will show the filled info with comments textbox. 
The user will fill comments can click on `Apply`  to call the rest command.
![image](https://user-images.githubusercontent.com/32794267/115899079-f39cbc00-a47b-11eb-9a0b-fda8779adf7d.png)
![image](https://user-images.githubusercontent.com/32794267/115899193-16c76b80-a47c-11eb-8682-f8eb63fbf0e6.png)

**Comment by syntrydy** [comment]
Adding more comment to clarify this:

**For example, let’s say I update two clients
Before these are executed, they should be stored.
And then when I’m ready to “commit” my changes, I hit a Commit button, at which point the Admin UI asks me for a comment about my changes.
Then an audit log is created with my attempted changes and a transaction id. This should include the API called with all parameters
Then each command is run
And a success note, with the transaction id.
If a command is unsuccessful, all my changes for that commit should be backed out.

**Comment by duttarnab** [comment]
Already implemented along with audit logs for OIDC Clients screen. Need to be replicated for other plugins. This will addressed using screen-specific tickets.
