### ISSUE TITLE
`Custom Properties (key/values)`  field is missing in Custom scripts

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/gluu-admin-ui#97]
`Custom Properties (key/values)`  field is missing in Custom scripts.

![image](https://user-images.githubusercontent.com/32794267/115693754-d84b8700-a37d-11eb-8680-65c1f628caa0.png)

**Comment by syntrydy** [comment]
@duttarnab if pôssible we need a generic component that can be reused for similar cases

**Comment by duttarnab** [comment]
Created a generic component. But it needs improvement.
